name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macOS-latest]
        python_version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Create virtualenv
      shell: bash
      run: |
        pip install virtualenv
        python -m virtualenv venv
    - name: Install dependencies
      shell: bash
      run: |
        pip install poetry
        source venv/bin/activate || source venv/Scripts/activate
        poetry install
    - name: Run tests
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        make test
    - name: Package
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        pip install pyinstaller==3.5
        make package
    #- name: Upload packages
    #  uses: actions/upload-artifact@v2-preview
    #  with:
    #    name: builds-${{ runner.os }}
    #    path: dist/activitywatch-*.*

